services:
  radar-tracker:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: radar-tracker-app

    ports:
      - "127.0.0.1:5000:5000"

    environment:
      FLASK_ENV: development

    restart: unless-stopped