"""DynamoDB schema definition and item builders for the assessments table.

This module defines:
- Table schema (for IaC reference)
- Item shape builders for each status
- Validation helpers for item size

This does NOT import boto3. It produces plain dicts suitable for:
- Step Functions DynamoDB service integration (PutItem/UpdateItem)
- Tests
- Documentation

The engine and Lambda handlers do NOT import this module.
Only Step Functions orchestration (and future IaC) consume these definitions.
"""

from datetime import datetime, timezone
from typing import Any, Dict, List, Optional
import json

# ===========================================================================
# TABLE SCHEMA
# ===========================================================================

TABLE_NAME = "secure-design-advisor-assessments"

TABLE_SCHEMA = {
    "TableName": TABLE_NAME,
    "KeySchema": [
        {"AttributeName": "assessment_id", "KeyType": "HASH"},
    ],
    "AttributeDefinitions": [
        {"AttributeName": "assessment_id", "AttributeType": "S"},
    ],
    "BillingMode": "PAY_PER_REQUEST",
}

# ===========================================================================
# STATUS MODEL
# ===========================================================================

STATUS_PROCESSING = "PROCESSING"
STATUS_COMPLETED = "COMPLETED"
STATUS_FAILED = "FAILED"

VALID_STATUSES = {STATUS_PROCESSING, STATUS_COMPLETED, STATUS_FAILED}

# Valid transitions
VALID_TRANSITIONS = {
    STATUS_PROCESSING: {STATUS_COMPLETED, STATUS_FAILED},
}

# ===========================================================================
# ITEM BUILDERS
# ===========================================================================


def build_processing_item(
    assessment_id: str,
    input_data: dict,
    created_at: Optional[str] = None,
) -> dict:
    """
    Build the DynamoDB item for PersistProcessing state.

    This is a PutItem operation — creates the initial record.

    Args:
        assessment_id: UUID generated by Step Functions (States.UUID())
        input_data: Validated assessment input (from Validate Lambda output)
        created_at: ISO 8601 timestamp (defaults to now)

    Returns:
        Plain dict representing the DynamoDB item.
    """
    now = created_at or _now_iso()
    return {
        "assessment_id": assessment_id,
        "status": STATUS_PROCESSING,
        "created_at": now,
        "updated_at": now,
        "input": input_data,
    }


def build_completed_update(
    result: dict,
    completed_at: Optional[str] = None,
) -> dict:
    """
    Build the update expression values for PersistCompleted state.

    This is an UpdateItem operation on an existing PROCESSING item.

    Args:
        result: Canonical AssessmentResult from Build Result Lambda
        completed_at: ISO 8601 timestamp (defaults to now)

    Returns:
        Dict with fields to update.
    """
    now = completed_at or _now_iso()
    return {
        "status": STATUS_COMPLETED,
        "result": result,
        "completed_at": now,
        "updated_at": now,
    }


def build_failed_update(
    error_type: str,
    error_message: str,
    failed_at: Optional[str] = None,
) -> dict:
    """
    Build the update expression values for PersistFailed state.

    This is an UpdateItem on an existing PROCESSING item.

    Args:
        error_type: Error classification (e.g., "ProcessingError")
        error_message: Human-readable error description
        failed_at: ISO 8601 timestamp (defaults to now)

    Returns:
        Dict with fields to update.
    """
    now = failed_at or _now_iso()
    return {
        "status": STATUS_FAILED,
        "error": {
            "type": error_type,
            "message": error_message,
        },
        "failed_at": now,
        "updated_at": now,
    }


# ===========================================================================
# SIZE GUARDRAIL
# ===========================================================================

DYNAMODB_MAX_ITEM_SIZE_BYTES = 400 * 1024  # 400 KB
SIZE_WARNING_THRESHOLD_BYTES = 300 * 1024  # Warn at 300 KB


def estimate_item_size(item: dict) -> int:
    """Estimate DynamoDB item size in bytes (approximation via JSON)."""
    return len(json.dumps(item, ensure_ascii=False).encode("utf-8"))


def check_item_size(item: dict) -> dict:
    """
    Check if item is within DynamoDB size limits.

    Returns:
        { "size_bytes": int, "within_limit": bool, "needs_s3_offload": bool }
    """
    size = estimate_item_size(item)
    return {
        "size_bytes": size,
        "within_limit": size <= DYNAMODB_MAX_ITEM_SIZE_BYTES,
        "needs_s3_offload": size > SIZE_WARNING_THRESHOLD_BYTES,
    }


# ===========================================================================
# HELPERS
# ===========================================================================


def _now_iso() -> str:
    """Current UTC timestamp in ISO 8601 format."""
    return datetime.now(timezone.utc).isoformat()
