version = 0.1

[default.global.parameters]
stack_name = "sda-dev"
region = "us-east-1"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "sda-dev"
parameter_overrides = "Stage=dev"
