import type { CompanyData } from "./types";

export const companiesData: CompanyData[] = [
  // === EMPRESAS ARGENTINAS ===
  {
    id: "mercadolibre",
    name: "Mercado Libre",
    group: "argentina",
    history: "Fundada en 1999 en Buenos Aires por Marcos Galperin. Hoy es la empresa de tecnología más valiosa de Latinoamérica.",
    focus: "E-commerce, fintech (Mercado Pago), logística (Mercado Envíos) y soluciones de crédito para la región.",
    culture: "Emprendedora, ágil, con foco en datos. Promueve la autonomía y el aprendizaje continuo.",
    technologies: ["Java", "Go", "React", "Node.js", "AWS", "Machine Learning", "Kotlin"],
    hiringRoles: ["Software Engineer", "Data Analyst", "SRE", "Product Designer", "DevOps"],
    studentPrograms: "IT Bootcamp (programa de formación para nuevos talentos sin experiencia previa).",
    funFact: "Procesa más de 40 compras por segundo en toda Latinoamérica.",
    url: "https://www.mercadolibre.com.ar",
  },
  {
    id: "globant",
    name: "Globant",
    group: "argentina",
    history: "Fundada en 2003 en La Plata por cuatro amigos. Hoy cotiza en NYSE y tiene más de 27.000 empleados.",
    focus: "Consultoría y desarrollo de software para grandes empresas globales como Disney, Google y Electronic Arts.",
    culture: "Innovación, comunidades internas (pods/studios), certificaciones y hackathons constantes.",
    technologies: ["React", "Angular", "Java", "Python", "AWS", "AI/ML", "Salesforce"],
    hiringRoles: ["Web Developer", "QA Engineer", "UX Researcher", "Cloud Architect", "Data Engineer"],
    studentPrograms: "Globant University y programas Back to the Future para jóvenes.",
    funFact: "Crearon la experiencia digital de los parques de Disney.",
    url: "https://www.globant.com",
  },
  {
    id: "despegar",
    name: "Despegar",
    group: "argentina",
    history: "Nació en 1999. Es la agencia de viajes online líder de Latinoamérica.",
    focus: "Plataforma de viajes: vuelos, hoteles, paquetes y experiencias turísticas.",
    culture: "Orientada a producto, data-driven, con equipos multidisciplinarios.",
    technologies: ["Java", "Kotlin", "React", "Python", "AWS", "Elasticsearch"],
    hiringRoles: ["Backend Developer", "Frontend Developer", "Data Scientist", "Product Manager"],
    funFact: "Opera en 20 países y gestiona millones de búsquedas de viajes por día.",
    url: "https://www.despegar.com.ar",
  },
  {
    id: "uala",
    name: "Ualá",
    group: "argentina",
    history: "Fundada en 2017 por Pierpaolo Barbieri. Busca democratizar las finanzas en la región.",
    focus: "Fintech: tarjeta prepaga, inversiones, préstamos, seguros y pagos digitales.",
    culture: "Startup intenso, crecimiento acelerado, diversidad e inclusión financiera.",
    technologies: ["Kotlin", "Swift", "React Native", "Python", "AWS", "Kafka"],
    hiringRoles: ["Mobile Developer", "Backend Engineer", "Data Analyst", "Compliance"],
    studentPrograms: "Programa de pasantías para estudiantes universitarios.",
    funFact: "Superó los 8 millones de usuarios en Argentina en menos de 6 años.",
    url: "https://www.uala.com.ar",
  },
  {
    id: "pomelo",
    name: "Pomelo",
    group: "argentina",
    history: "Fundada en 2021. Infraestructura fintech para que otras empresas lancen productos financieros.",
    focus: "Plataforma de infraestructura para emisión de tarjetas, procesamiento de pagos y banking-as-a-service.",
    culture: "Remoto-first, transparencia radical, colaboración sin jerarquías rígidas.",
    technologies: ["Go", "Kotlin", "React", "AWS", "Terraform", "Kubernetes"],
    hiringRoles: ["Backend Engineer", "Platform Engineer", "Product Designer", "QA"],
    funFact: "Permite que cualquier empresa pueda lanzar su propia tarjeta en semanas.",
    url: "https://www.pomelo.la",
  },
  {
    id: "modo",
    name: "MODO",
    group: "argentina",
    history: "Lanzada en 2020 como billetera digital impulsada por los bancos argentinos.",
    focus: "Pagos digitales interoperables entre bancos y comercios en Argentina.",
    culture: "Colaborativa, uniendo competidores por un objetivo común: digitalizar pagos.",
    technologies: ["Node.js", "React Native", "AWS", "Microservicios"],
    hiringRoles: ["Mobile Developer", "Backend Developer", "UX Designer", "Product Manager"],
    funFact: "Conecta más de 35 bancos y billeteras en una sola experiencia.",
    url: "https://www.modo.com.ar",
  },
  {
    id: "satellogic",
    name: "Satellogic",
    group: "argentina",
    history: "Fundada en 2010. Primera empresa argentina en poner satélites propios en órbita.",
    focus: "Constelación de satélites para captura de imágenes de la Tierra con resolución submétrica.",
    culture: "Científica e ingenieril, multidisciplinaria, con visión de largo plazo.",
    technologies: ["Python", "C++", "Machine Learning", "Computer Vision", "AWS"],
    hiringRoles: ["Embedded Engineer", "ML Engineer", "Data Scientist", "Systems Engineer"],
    funFact: "Planean tener 300+ satélites para mapear todo el planeta cada semana.",
    url: "https://www.satellogic.com",
  },

  // === EMPRESAS INTERNACIONALES CON PRESENCIA EN ARGENTINA ===
  {
    id: "ibm",
    name: "IBM",
    group: "internacional",
    history: "Fundada en 1911 en EE.UU. Más de 100 años de historia en tecnología. Presente en Argentina desde 1923.",
    focus: "Cloud híbrida, inteligencia artificial (Watson), consultoría tecnológica y servicios empresariales.",
    culture: "Inclusiva, con foco en innovación responsable y desarrollo profesional continuo.",
    technologies: ["Red Hat", "Kubernetes", "Python", "Java", "Quantum Computing", "AI"],
    hiringRoles: ["Cloud Engineer", "Data Scientist", "Consultant", "Security Analyst", "Developer"],
    studentPrograms: "IBM SkillsBuild (formación gratuita) y programa de pasantías.",
    funFact: "Ha ganado más de 150.000 patentes, más que cualquier otra empresa en la historia.",
    url: "https://www.ibm.com/ar-es",
  },
  {
    id: "aws",
    name: "AWS (Amazon Web Services)",
    group: "internacional",
    history: "Lanzada en 2006. Es el proveedor de nube más grande del mundo. Tiene oficinas en Buenos Aires.",
    focus: "Servicios de cloud computing: cómputo, almacenamiento, bases de datos, IA, IoT y más.",
    culture: "Customer obsession, ownership, frugalidad y bias for action (los 16 Leadership Principles).",
    technologies: ["AWS Services", "Python", "Java", "Go", "Terraform", "Serverless"],
    hiringRoles: ["Solutions Architect", "Cloud Support Engineer", "Technical Account Manager"],
    studentPrograms: "AWS re/Start (programa gratuito de formación cloud para principiantes).",
    funFact: "Tiene más de 200 servicios y alimenta el 32% del tráfico de internet global.",
    url: "https://aws.amazon.com",
  },
  {
    id: "microsoft",
    name: "Microsoft",
    group: "internacional",
    history: "Fundada en 1975 por Bill Gates. En Argentina desde los '90 con oficinas en Buenos Aires.",
    focus: "Cloud (Azure), productividad (Office 365), IA (Copilot), gaming (Xbox) y developer tools.",
    culture: "Growth mindset, inclusión, aprendizaje continuo y balance vida-trabajo.",
    technologies: ["Azure", "C#", ".NET", "TypeScript", "Python", "AI/ML"],
    hiringRoles: ["Cloud Solution Architect", "Software Engineer", "Support Engineer", "PM"],
    studentPrograms: "Microsoft Learn Student Ambassadors y pasantías de verano.",
    funFact: "GitHub (propiedad de Microsoft) tiene más de 100 millones de desarrolladores.",
    url: "https://www.microsoft.com/es-ar",
  },
  {
    id: "google",
    name: "Google",
    group: "internacional",
    history: "Fundada en 1998. Tiene oficinas en Buenos Aires enfocadas en publicidad y cloud.",
    focus: "Búsqueda, publicidad digital, Google Cloud, Android, YouTube e inteligencia artificial.",
    culture: "Innovación radical, 20% time para proyectos personales, datos para todo.",
    technologies: ["Go", "Python", "Kubernetes", "TensorFlow", "GCP", "Angular"],
    hiringRoles: ["Software Engineer", "Cloud Engineer", "UX Designer", "Data Analyst"],
    studentPrograms: "Google Summer of Code, Google Developer Student Clubs.",
    funFact: "Procesa más de 8.500 millones de búsquedas por día.",
    url: "https://careers.google.com",
  },
  {
    id: "oracle",
    name: "Oracle",
    group: "internacional",
    history: "Fundada en 1977. Pionera en bases de datos. Presente en Argentina hace décadas.",
    focus: "Bases de datos, ERP empresarial, Oracle Cloud Infrastructure (OCI) y aplicaciones SaaS.",
    culture: "Corporativa pero con programas fuertes de formación interna y certificaciones.",
    technologies: ["Java", "SQL", "Oracle DB", "OCI", "Kubernetes", "APEX"],
    hiringRoles: ["Database Administrator", "Cloud Engineer", "Consultant", "Sales Engineer"],
    studentPrograms: "Oracle Next Education (ONE) — programa gratuito de formación tech.",
    funFact: "Java (creado por Sun, comprada por Oracle) se ejecuta en 3 mil millones de dispositivos.",
    url: "https://www.oracle.com/ar",
  },
  {
    id: "sap",
    name: "SAP",
    group: "internacional",
    history: "Fundada en 1972 en Alemania. Líder mundial en software empresarial. Oficinas en Buenos Aires.",
    focus: "ERP, gestión de recursos humanos (SuccessFactors), supply chain y analytics empresarial.",
    culture: "Foco en diversidad, sustentabilidad y desarrollo profesional estructurado.",
    technologies: ["ABAP", "SAP HANA", "SAP BTP", "UI5", "Python", "Cloud Foundry"],
    hiringRoles: ["SAP Consultant", "Developer", "UX Designer", "Data Analyst", "Support"],
    studentPrograms: "SAP Young Professionals Program (formación + certificación + empleo).",
    funFact: "El 77% de las transacciones comerciales del mundo pasan por un sistema SAP.",
    url: "https://www.sap.com/argentina",
  },
  {
    id: "deloitte",
    name: "Deloitte",
    group: "internacional",
    history: "Fundada en 1845 en Londres. Una de las Big 4 de consultoría. Fuerte en tecnología en Argentina.",
    focus: "Consultoría tecnológica, ciberseguridad, cloud, transformación digital y auditoría.",
    culture: "Desarrollo de carrera estructurado, mentorías, networking y proyectos de alto impacto.",
    technologies: ["SAP", "Salesforce", "AWS", "Azure", "ServiceNow", "Python"],
    hiringRoles: ["IT Consultant", "Cyber Analyst", "Cloud Engineer", "Developer", "Business Analyst"],
    studentPrograms: "Programa de Jóvenes Profesionales con rotación entre áreas.",
    funFact: "Tiene más de 415.000 empleados en 150 países.",
    url: "https://www2.deloitte.com/ar",
  },
  {
    id: "accenture",
    name: "Accenture",
    group: "internacional",
    history: "Originada en 1989. Gigante de consultoría y tecnología. Más de 9.000 empleados en Argentina.",
    focus: "Consultoría, tecnología, outsourcing, estrategia digital y operaciones empresariales.",
    culture: "Inclusiva, con carrera estructurada, mentorías y movilidad global.",
    technologies: ["Java", "SAP", "Salesforce", "AWS", "Azure", "AI/Automation"],
    hiringRoles: ["Software Engineer", "Consultant", "Cloud Developer", "QA", "Project Manager"],
    studentPrograms: "Accenture Academy y programa de ingreso para recién graduados.",
    funFact: "Es una de las mayores empleadoras de tecnología en Argentina.",
    url: "https://www.accenture.com/ar-es",
  },
  {
    id: "ey",
    name: "EY (Ernst & Young)",
    group: "internacional",
    history: "Fundada en 1989. Otra de las Big 4 con fuerte inversión en tecnología en Argentina.",
    focus: "Consultoría, auditoría, impuestos y servicios de tecnología y transformación digital.",
    culture: "Building a better working world. Inclusión, formación continua y proyectos globales.",
    technologies: ["SAP", "Python", "Power BI", "Azure", "RPA", "Blockchain"],
    hiringRoles: ["Tech Consultant", "Data Analyst", "Cybersecurity Analyst", "Developer"],
    studentPrograms: "EY Launch — programa para estudiantes con formación y mentoría.",
    funFact: "Invierte más de 700 millones de dólares al año en tecnología e innovación.",
    url: "https://www.ey.com/es_ar",
  },
  {
    id: "kyndryl",
    name: "Kyndryl",
    group: "internacional",
    history: "Separada de IBM en 2021. Es el mayor proveedor de servicios de infraestructura IT del mundo.",
    focus: "Gestión de infraestructura IT, cloud, modernización de mainframes y servicios gestionados.",
    culture: "The Heart of Progress. Foco en personas, innovación y alianzas tecnológicas.",
    technologies: ["Red Hat", "AWS", "Azure", "VMware", "Mainframe", "Automation"],
    hiringRoles: ["Infrastructure Engineer", "Cloud Specialist", "Security Analyst", "SRE"],
    studentPrograms: "Programa de desarrollo para graduados recientes.",
    funFact: "Gestiona la infraestructura tecnológica de 75 de las 100 empresas Fortune.",
    url: "https://www.kyndryl.com",
  },
  {
    id: "huawei",
    name: "Huawei",
    group: "internacional",
    history: "Fundada en 1987 en China. Presente en Argentina con foco en telecomunicaciones y cloud.",
    focus: "Telecomunicaciones, redes 5G, cloud computing y dispositivos inteligentes.",
    culture: "Orientada a resultados, con programas de transferencia de conocimiento y becas.",
    technologies: ["5G", "Cloud", "AI", "IoT", "OpenEuler", "Kunpeng"],
    hiringRoles: ["Network Engineer", "Cloud Engineer", "R&D Engineer", "Sales Engineer"],
    studentPrograms: "Seeds for the Future — becas y formación para estudiantes latinoamericanos.",
    funFact: "Invierte el 25% de sus ingresos anuales en investigación y desarrollo.",
    url: "https://www.huawei.com/ar",
  },
  {
    id: "samsung",
    name: "Samsung",
    group: "internacional",
    history: "Fundada en 1938 en Corea del Sur. En Argentina tiene presencia en electrónica y desarrollo.",
    focus: "Electrónica de consumo, semiconductores, móviles, smart TVs y ecosistema IoT.",
    culture: "Innovación constante, calidad, investigación y desarrollo a largo plazo.",
    technologies: ["Tizen", "Android", "Kotlin", "C++", "AI", "IoT"],
    hiringRoles: ["Mobile Developer", "QA Engineer", "Product Manager", "Sales"],
    studentPrograms: "Samsung Innovation Campus — formación en IA y IoT para jóvenes.",
    funFact: "Fabrica el 20% de las exportaciones totales de Corea del Sur.",
    url: "https://www.samsung.com/ar",
  },
];
