import type { CommunityData } from "./types";

export const communitiesData: CommunityData[] = [
  {
    id: "aws-ug",
    name: "AWS User Groups Argentina",
    description: "Comunidad de profesionales y entusiastas de Amazon Web Services. Organizan meetups mensuales donde comparten experiencias reales con servicios cloud.",
    activities: ["Meetups presenciales", "Workshops hands-on", "Charlas técnicas", "Networking"],
    audience: "Cualquier persona interesada en cloud computing, desde principiantes hasta expertos.",
    url: "https://aws.amazon.com/developer/community/usergroups/",
    accent: "peach",
  },
  {
    id: "gdg",
    name: "Google Developer Groups (GDG)",
    description: "Grupos locales de desarrolladores apasionados por tecnologías de Google. Organizan eventos como DevFest, estudio de Android y workshops de Firebase.",
    activities: ["DevFest anual", "Study Jams", "Codelabs", "Workshops de tecnologías Google"],
    audience: "Desarrolladores de todos los niveles interesados en tecnologías Google.",
    url: "https://developers.google.com/community/gdg",
    accent: "mint",
  },
  {
    id: "women-techmakers",
    name: "Women Techmakers",
    description: "Programa global de Google que brinda visibilidad, comunidad y recursos a mujeres en tecnología. Organizan eventos, mentorías y becas.",
    activities: ["Eventos de visibilidad", "Mentorías", "Workshops técnicos", "IWD (International Women's Day)"],
    audience: "Mujeres y personas no binarias en tecnología o interesadas en ingresar al sector.",
    url: "https://developers.google.com/womentechmakers",
    accent: "lavender",
  },
  {
    id: "pyladies",
    name: "PyLadies",
    description: "Grupo internacional que promueve la diversidad en la comunidad Python. Organizan meetups, talleres de programación y mentoría para principiantes.",
    activities: ["Talleres de Python", "Mentorías", "Charlas inclusivas", "Sprints de código"],
    audience: "Mujeres e identidades subrepresentadas interesadas en Python.",
    url: "https://pyladies.com",
    accent: "mint",
  },
  {
    id: "ibm-community",
    name: "IBM Community",
    description: "Red de profesionales y entusiastas de tecnologías IBM. Acceso a recursos, foros, eventos y programas de certificación.",
    activities: ["Foros técnicos", "Webinars", "Challenges", "Acceso a IBM Cloud"],
    audience: "Profesionales IT y estudiantes interesados en enterprise technology.",
    url: "https://community.ibm.com",
    accent: "lavender",
  },
  {
    id: "meetups-tech",
    name: "Meetups de Tecnología",
    description: "Argentina tiene decenas de meetups activos: JavaScript, React, Data Science, DevOps, UX y más. Son gratuitos, presenciales o virtuales, y perfectos para empezar.",
    activities: ["Charlas técnicas", "Lightning talks", "Networking", "Pizza y cerveza"],
    audience: "Cualquier persona con curiosidad por la tecnología. No se requiere experiencia.",
    url: "https://www.meetup.com/find/?keywords=tecnologia&location=ar--Buenos+Aires",
    accent: "peach",
  },
  {
    id: "hackathons",
    name: "Hackathons",
    description: "Eventos intensivos donde equipos desarrollan un proyecto en 24-48 horas. Son la mejor forma de aprender haciendo, conocer gente y ganar experiencia real.",
    activities: ["Desarrollo en equipo", "Mentorías en vivo", "Presentaciones", "Premios"],
    audience: "Estudiantes, principiantes y profesionales. Muchos aceptan participantes sin experiencia.",
    url: "https://mlh.io",
    accent: "mint",
  },
];
